name: Static Analysis
on: [push, pull_request]
concurrency:
  group: static-analysis-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Get dependencies
      run: |
        # Needed for github.com/google/go-tspi/tspi
        sudo apt-get install libtspi-dev
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install golang.org/x/lint/golint@latest

    - name: Vet
      run: go vet -tags ci ./...

    - name: Goimports
      run: test -z $(goimports -e -d . | tee /dev/stderr)

    - name: Gocyclo
      run: gocyclo -over 30 .

    - name: Golint
      run: golint -set_exit_status $(go list -tags ci ./...)

    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
        install-go: false
